apiVersion: v1
kind: ConfigMap
metadata:
  name: init-schema-configmap
  namespace: rest-api-test-sandbox-ns
data:
  create-schema.sql: |
    create schema blog;

    create table blog.post (
      id serial primary key,
      title text not null,
      content text not null,
      date timestamp default now()
    );