apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-test
  namespace: rest-api-test-sandbox-ns
  labels:
    app: rest-api-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-api-test
  template:
    metadata:
      labels:
        app: rest-api-test
    spec:
      containers:
        - name: rest-api-test
          image: docker.io/jpdev99/rest-api-test:sandbox
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: postgres
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
      imagePullSecrets:
        - name: regcred